name: Download Projects

on:
    schedule:
        -   cron: 34 0 * * *
    workflow_dispatch:

permissions: write-all

jobs:
    MoonShine:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "3.x" ]
        with:
            project: MoonShine Admin Panel ${{ matrix.version }}
            paths: source/moonshine/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/moonshine-software/moonshine/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=moonshine \
                    --ver=${{ matrix.version }} \
                    --copy=src/Laravel/lang/en \
                    --only-copy
                
                php app/translate.php
